### ISSUE TITLE
chromeLike filter is not respecting alpha channel when applied to mipmaps

### ISSUE THREAD

**Issue by malloth** [usefulness/easylauncher-gradle-plugin#102]
On older Android versions (which do not support adaptive icons) I was expecting this plugin to respect the alpha channel of the original image as a filter boundary. Especially when using **chromeLike** filter. Below is the icon which is being produced in the version 3.8.0 of this plugin. The ribbon should NOT be drawn on transparent pixels for **chromeLike** filter.

![ic_launcher](https://user-images.githubusercontent.com/3379702/98841926-15176780-2449-11eb-86df-b26f439c5837.png)

Can you please add such flag to this filter (by default set to true), so that we can have the same effect as with adaptive icons?

**Comment by mateuszkwiecinski** [comment]
Hey @malloth 👋  Thank you for reporting the issue 🙏 
I've finally found a time to take a stab at this and as a result I just released version 3.9.0 which should have it fixed. I changed the behavior as it never intended to look as on the image you posted. 
Please let me know if works as you would expect

**Comment by malloth** [comment]
Thank you Mateusz. It works nicely now! 🍻
