### ISSUE TITLE
[Question] - Is it possible to add versionName?

### ISSUE THREAD

**Issue by GuilhE** [usefulness/easylauncher-gradle-plugin#112]
First of all, thank you for the work you've put into this plugin's new era! 👍 

My setup:

```
easylauncher {
//    defaultFlavorNaming(true)
    productFlavors {
        create("dev") {
            filters(customRibbon(label = "DEV ${android.defaultConfig.versionName}", ribbonColor = "#AB9F1C13"))
        }
        create("qa") {
            filters(customRibbon(label = "QA ${android.defaultConfig.versionName}", ribbonColor = "#BCD5C223"))
        }
    }
}
```
```
productFlavors {
        create("qa") {
            applicationIdSuffix = ".app.qa"
            versionName = "1.0.3"
        }

        create("dev") {
            applicationIdSuffix = ".app.dev"
            versionName = "1.0.4"
        }
}
```
But I guess `easylauncher` runs first and there's no `versionName` yet created thus I end up with "DEV/QA null". If I move `easylauncher` into `project.afterEvaluation` my configurations are discarded which makes me think that  `easylauncher`  already have run with defaults.

So, without global variables, is it possible to extract the current flavor versions and append it to ColorRibbonFilter label? 😃 
Best regards.

**Comment by mateuszkwiecinski** [comment]
Hey @GuilhE 👋  Thanks for those kind words 🙏 

So from what I can see your issue is caused by the fact you access defaultConfig's versionName while it is not set. Looking at configuration you posted you should instead use:
```
easylauncher {
//    defaultFlavorNaming(true)
    productFlavors {
        create("dev") {
            filters(customRibbon(label = "DEV ${android.productFlavors.dev.versionName}", ribbonColor = "#AB9F1C13"))
        }
        create("qa") {
            filters(customRibbon(label = "QA ${android. productFlavors.qa.versionName}", ribbonColor = "#BCD5C223"))
        }
    }
}
```
or if that's kotlin-dsl then `android.productFlavors.getByName("dev").versionName`
I've added a sample reproducing your use case to make sure it won't break in the future in #113

Btw. you probably want use `register()` instead of `create()` to let Gradle configure things lazily (both for the Easylauncher and for AGP flavors)

**Comment by GuilhE** [comment]
Hello,
It worked!

> Hey @GuilhE 👋 Thanks for those kind words 🙏

You deserve 😉 

> Btw. you probably want use `register()` instead of `create()` to let Gradle configure things lazily (both for the Easylauncher and for AGP flavors)

Thanks for the tip and actually I had to use register() 'cause with create() would throw no flavour found.
 
> or if that's kotlin-dsl then `android.productFlavors.getByName("dev").versionName` (or something similar, sorry kotlin-dsl doesn't work for me so I can't confirm :/)

Yup correct!

> I've added a sample reproducing your use case to make sure it won't break in the future in #113

👌 

Here's the output (yay!):

![Screenshot 2021-01-14 at 11 38 18](https://user-images.githubusercontent.com/2677139/104586187-0e7dba00-565d-11eb-89c8-b0b4441130b4.png)

**Comment by mateuszkwiecinski** [comment]
Great to hear! I'm happy I could help and the plugin works for you too 🎉
