### ISSUE TITLE
Support translucent color for ChromeLikeFilter

### ISSUE THREAD

**Issue by brudaswen** [usefulness/easylauncher-gradle-plugin#136]
Setting a translucent color for `ChromeLikeFilter` creates PNGs that do not show the original icon below.

![chromelike_alpha](https://user-images.githubusercontent.com/790875/112721645-56df1100-8f05-11eb-8316-2f3ed76f5c4a.PNG)

Will prepare a PR in a second.

**Comment by brudaswen** [comment]
Thanks a lot for this great plugin. Was looking forward to have support for adaptive icons and not it works. 🤟 Found some small issues while trying to integrate it into my current project. Hope my contribution helps.

**Comment by mateuszkwiecinski** [comment]
Hey @brudaswen 👋 Thank's for reporting the issue and for the fix. 
I merged the PR, and I'll try to figure out how to run screenshot tests tomorrow to make sure it doesn't break in the future. I'll try to make the release with your fixes by Monday morning. 
And once again: thanks for the help 🙏
