### ISSUE TITLE
Gradle 7.0 + AGP 4.2.0 Warning: Execution optimizations have been disabled for task ':app:extractDeepLinksBuildVariant' to ensure correctness due to the following reasons:

### ISSUE THREAD

**Issue by mateuszkwiecinski** [usefulness/easylauncher-gradle-plugin#165]
When running a build on a project with AGP 4.2.0 and Gradle 7.0 it shows a warning message:
```
Execution optimizations have been disabled for task ':app:extractDeepLinksBuildVariant' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '~/../app/build/generated/easylauncher/res/devDebug/navigation'. Reason: Task ':app:extractDeepLinksBuildVariant' uses this output of task ':app:easylauncherBuildVariant' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

The issue has been reported here: https://issuetracker.google.com/issues/187096666

The workaround would do declare an explicit dependency:
```
/**
 * Workaround for: https://issuetracker.google.com/issues/187096666
 */
tasks.withType(com.android.build.gradle.tasks.ExtractDeepLinksTask).configureEach {
    def easylauncherTaskName = name.replace("extractDeepLinks", "easylauncher")
    // Workaround for: https://github.com/gradle/gradle/issues/8057
    if (tasks.getNames().contains(easylauncherTaskName)) {
        dependsOn(easylauncherTaskName)
    }
}
```

it is not technically valid, but it shouldn't break anything as this plugin doesn't write anything to its `/navigation` subdirectory 🤷

**Comment by eugene-kirzhanov** [comment]
Have the same issue. Using jetpack navigation component (with safe args plugin) and this easy-launcher plugin (3.10.3 or 4.0.0)

**Comment by mateuszkwiecinski** [comment]
FYI: according to the comment in linked issue https://issuetracker.google.com/issues/187096666#comment3 that's not related to navigation component but Android Gradle Plugin in general

I'm not eager to add a workaround to the plugin because, as far as I undrestand, that's a bug on AGP's side 🤷 
If the warning bothers you, feel free to use the workaround attached to the issue above ☝️
