### ISSUE TITLE
Use platform-independent default font

### ISSUE THREAD

**Issue by brudaswen** [usefulness/easylauncher-gradle-plugin#178]
Currently, the used default font is system-dependent such that the launcher icon is slightly different if build on different machines.

I realized this while running the screenshot tests. The current screenshots seem to be generated on macOS 11 that uses "Helvetica Neue" as default font. When I build the screenshots on Windows, the results are slightly different.

### Proposal
Use `Roboto` in case now font is provided such that the generated launcher icon is independent of the build system.

## Example

|macOS|Windows|
|---|---|
|![macOS](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/sample/example-icon-round/screenshots/Icons_default(keep-default).png?raw=true)|![Windows](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/sample/example-icon-round/screenshots/Icons_default(ignore-default).png?raw=true)|

**Comment by mateuszkwiecinski** [comment]
Wow! I haven't though about the default font. And actually didn't realise I test on macos only, I somehow believed I made screenshots run on ubuntu which made me feel safer it works everywhere 🤦 
What you suggesting is definitelly a behavior we would like to introduce here 👍 

I'll try to find time later today to verify the behavior manually, will look at screenshot tests why they didn't fail previously and will relese your fix together with #166 bumping major plugin version.
