### ISSUE TITLE
Request to add support for banner icon

### ISSUE THREAD

**Issue by peerless2012** [usefulness/easylauncher-gradle-plugin#228]
First , I am so glad that you build this plugin , and it makes it easy to build different flavor whit different icon.

I'm working on to make my app run on TV, so it need to setup the banner icon (ic_launcher_banner 16 : 9), but the plugin does't support to modify the banner icon.

So it may be better to support that.

Original issue: 
[Request to add support for banner icon](https://github.com/akaita/easylauncher-gradle-plugin/issues/40)

**Comment by peerless2012** [comment]
`android:banner="@mipmap/ic_launcher_banner"` is for Android TV devices.

I will try your solotions.

**Comment by peerless2012** [comment]
```
classpath 'com.android.tools.build:gradle:4.2.2'
classpath "com.project.starter:easylauncher:4.1.1"
```
```
What went wrong:
A problem occurred evaluating script.
> Could not get unknown property 'true' for project ':app' of type org.gradle.api.Project.

```

Error line:
```
// Use flavor name for default ribbon, instead of the type name
defaultFlavorNaming = true
```

**Comment by mateuszkwiecinski** [comment]
I'm closing the issue for now. If you're still experiencing any issues with the plugin, please do share a repro repository 👀

**Comment by emouawad** [comment]
@peerless2012 Have you been able to fix this? I have the same issue - this is a very nice plugin but it looks Android TV handles things differently.

https://developer.android.com/training/tv/start/start.html#banner
![image](https://user-images.githubusercontent.com/6771272/155592250-6cd6401f-0cf2-4868-af5e-748f4c15ffc2.png)

**Comment by peerless2012** [comment]
This is the my project main difference..

1. Create a banner icon with 512*288, and put it in mipmap-xxxhdpi
2. In AndroidManifest application, android:banner use that resource
3. put the 512*512 overlay icon to plugin
4. build apk and install on Android TV
5. You will see the overlay icon position is not right.
