### ISSUE TITLE
Gradle 7.3.3 compatibility

### ISSUE THREAD

**Issue by FowlingLight** [usefulness/easylauncher-gradle-plugin#266]
Hi !

First of all, thanks for this awesome plugin !

I'm upgrading an app to the latest Gradle stable version available (7.3.3 at the time of writting) and I'm facing some errors with the plugin, mainly missing annotations in the Manifest.

Here's one of the errors I'm getting

> In plugin 'com.akaita.android.easylauncher' type 'com.akaita.android.easylauncher.plugin.EasyLauncherTask' property 'androidManifestFiles' is missing an input or output annotation.
> 
> Reason: A property without annotation isn't considered during up-to-date checking.
>     
>     Possible solutions:
>       1. Add an input or output annotation.
>       2. Mark it as @Internal.
>     
> Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#missing_annotation for more details about this problem.

This issue is repeated for these variables :
- androidManifestFiles
- filters
- foregroundIconNames
- iconNames
- launcherIconNames

Has anyone else faced that issue?

**Comment by mateuszkwiecinski** [comment]
Yeah, `com.akaita.android.easylauncher` is the old, unmaintaned version of this plugin: https://github.com/akaita/easylauncher-gradle-plugin
This project highly benefits from it (hence the name), but contains all necessary changes needed to be compatible with the most recent gradle versions.
Just replace `com.akaita.android.easylauncher` with `com.starter.easylauncher` and should be all fine
