### ISSUE TITLE
Firebase distribution upload fails

### ISSUE THREAD

**Issue by emartynov** [usefulness/easylauncher-gradle-plugin#267]
Hi people, just a question, maybe you have an idea what is happening.

Recently we started getting errors while uploading apk to Firebase distribution:
```
...
Failed to run aapt dump badging: AndroidManifest.xml:69: error: ERROR getting 'android:icon' attribute: attribute is not a string value 
```

I checked our manifest files - we don't have any icon specification and I assume we rely on the plugin to add it during the build.

**Comment by emartynov** [comment]
Aha, exploring more I found https://github.com/pandulapeter/beagle/issues/89. So maybe it is not related to the plugin but an issue with some dependency.

**Comment by mateuszkwiecinski** [comment]
This plugin doesn't modify `android:icon` attribute 🤔 The way plugin works is it generates variant-specific icon based on resource pointed by the Manifest's `android:icon`. I'd advise you to inspect merged manifest and generated resources and check if there is anything highlighted as incompatible with your minimum sdk level.

Does the issue go away after you disable the plugin? Are you able to reproduce it manually when you run `aapt dump badging`? If it is an issue with the plugin - would you be able to provide a repro project?

Looking at the plugin implementation I can't find anything that would be incompatible 👀 Generated resource looks like [this](https://github.com/usefulness/easylauncher-gradle-plugin/blob/96cb5507183c8a027892f2cf476de74c43f05bc9/easylauncher/src/test/kotlin/com/project/starter/easylauncher/plugin/IconTransformerTest.kt#L49) where the genrated `layer-list` contains original resource from `android:icon` and generated png files - all of it should be supported on every sdk level

**Comment by emartynov** [comment]
Thank you so much for checking and messaging!! 

I found the situation similar to the ticket I posted - this time it is a biometrics library from Google.

I'm closing since irrelevant.
