### ISSUE TITLE
ResValues no longer work in 6.0.0

### ISSUE THREAD

**Issue by brudaswen** [usefulness/easylauncher-gradle-plugin#382]
Using `InternalArtifactType.GENERATED_RES` has the side-effect, that res values that are created using Gradle are no longer part of the build.

I updated one of the test apps which shows that the String value is no longer used and the build fails:
https://github.com/usefulness/easylauncher-gradle-plugin/commit/cd0bb0f964ee9013d75435726443d41d785975d7

One can also see that AS no longer recognizes the folder as a resource folder:
|`<6.0.0`|`6.0.0`|
|---|---|
|![image](https://user-images.githubusercontent.com/790875/201735594-aba667f9-15ea-4528-87f3-c54ff7c84f14.png)|![image](https://user-images.githubusercontent.com/790875/201735282-596f8e72-3de6-4e0f-a9a2-49050a2f81be.png)|

I tried to fix the issue, but was not lucky, yet:
https://github.com/usefulness/easylauncher-gradle-plugin/commit/c4148d1c029cfae1cedcd49ace9bb9e85ad44a7b

**Comment by mateuszkwiecinski** [comment]
Thanks for keeping an eye on the plugin 🙏 
Your fix looked so much reasonable, it made me test it against AGP `7.4.0-beta05` and `8.0.0-alpha08`. Surprise surprise, it seemed to work on them both... 🤷 This makes me believe this is another bug in 7.3.x version: this one looks _related_: https://issuetracker.google.com/issues/237421684 😞 

I came up with my proposal, based on your suggestion: https://github.com/usefulness/easylauncher-gradle-plugin/pull/383. 
I wasn't able to figure out "proper" workaround for AGP 7.3.X - it feels like this version is simply flawed and that's all, period :/

**Comment by brudaswen** [comment]
Thanks a lot for maintaining this super useful plugin. 🤗

Strange, I also stumbled upon the Google issue and thought it might cause problems. But even after updating to 7.4beta05, I could not build with the generated icons.

I will test your branch tomorrow, but this looks promising to fix the issue in 7.4. Thanks a lot for the quick help.

**Comment by mateuszkwiecinski** [comment]
The workaround has landed in #383 and has been released as `6.1.0`, but since AGP 7.4.1 is now available, and it solves almost all the issues (except #408), therfore I'm going to close this one 👀 Thanks again for the report!
