### ISSUE TITLE
Is it a must to use android.disableResourceValidation=true in latest AS/AGP?

### ISSUE THREAD

**Issue by bosphere** [usefulness/easylauncher-gradle-plugin#406]
Now that AS Electric Eel has been released together with AGP 7.4.0 as the recommended version, AGP will complain `Duplicate Resources` with the default setup. Is it a must to include `android.disableResourceValidation=true` in `gradle.properties`?

**Comment by mateuszkwiecinski** [comment]
As far I as remembered 7.4.0 is still flawed and proper fix for merging resources will available only in AGP 8.0 (with possible partial patch in 7.4.1) 🤷 As per my understanding, this plugin does things correctly, and it's AGP who does crazy things in AGP 7.3 and 7.4. I'll link related issuetracker links describing issues with 7.3 and 7.4:
https://issuetracker.google.com/issues/261329823 
https://issuetracker.google.com/issues/244063664

A simple answer is: `android.disableResourceValidation=true` should not be needed: 
	- if it works then great,
	- if it doesn't, and you're using AGP 7.3 or 7.4 - that's _expected_ and the `android.disableResourceValidation=true` should help
	- if it doesn't and you're using any other AGP version - I'm unaware of it and it should be investigated further

**Comment by StylianosGakis** [comment]
Just bumped to AGB 8.0.0 stable along with gradle 8.0.2 and it looks like removing the `android.disableResourceValidation=true`.
So that's good news, no more need for this workaround as I see it.
