### ISSUE TITLE
Vector icon support from Drawable not working

### ISSUE THREAD

**Issue by HashirLabs** [usefulness/easylauncher-gradle-plugin#441]
I have been using the plugin for quite sometime and it is working flawlessly, i have png icons and vector icons in mipmaps which has been working fine, however when i enabled below changes, the build fails, any guidlines please

`    iconNames = ["@mipmap/ic_launcher", "@mipmap/ic_launcher_round", "@mipmap/ic_launcher_foreground", "@drawable/tv_banner"]`

Please note that **@drawable/tv_banner** is the main issue here which is a vector image xml file

Below is the error 

Unsupported image format at D:\IT\Android\AndroidStudioProjects\<removed_path>\app\src\main\res\drawable\tv_banner.xml

**Comment by mateuszkwiecinski** [comment]
Hey 👋 
What's your use case? What's the `tv_banner.xml` file? 
Unfortunately, the plugin doesn't support adding badges to _any_ file. It only supports raster images (png, webp) or `<adaptive-icon />` resources used for [Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) feature. 

I now see how the Readme could be misleading, I'll try to clarify vector resources are only supported in context of adaptive icon foreground 👀

**Comment by HashirLabs** [comment]
hummm, i was assuming vector icons are supported based on Readme.

tv_banner.xml is a vector icon file which is used to display the banner icon when app is installed in tv devices. Like square and circle icons are displayed in phone with ribbons, i was trying to display ribbon for banners (which are used as app icons in tv) to differentiate the release , debug and other types of build types.

Is there any way we can acheive this?
