### ISSUE TITLE
Could not find method redRibbonFilter()

### ISSUE THREAD

**Issue by alexwyattdev** [usefulness/easylauncher-gradle-plugin#465]
I added the dependency/plugin to my project, if I don't do anything else it works and puts the "debug" ribbon on my icon, however I want to differentiate between debug and mock version, so I wanted to use the redRibbonFilter() or basically any other filters including custom ones to it and none of them are recognized:

`Could not find method redRibbonFilter() for arguments [] on ProductFlavor$AgpDecorated_Decorated{name=mock, dimension=environment, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=null, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=[], buildConfigFields={IS_MOCK=com.android.builder.internal.ClassFieldImpl@1c2f0af6}, resValues={}, proguardFiles=[], consumerProguardFiles=[], manifestPlaceholders={}, wearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor$AgpDecorated.`

**Comment by mateuszkwiecinski** [comment]
👋 
Please do follow [Advanced usage](https://github.com/usefulness/easylauncher-gradle-plugin#advanced-usage) section of the readme. You have to configure the plugin via `easylauncher { buildTypes {} }` extension, not `android { buildTypes {} }` like you do (this is where the `com.android.build.gradle.internal.dsl.ProductFlavor$AgpDecorated` comes from)
