### ISSUE TITLE
Launcher icon missing in Mac OS

### ISSUE THREAD

**Issue by theimpulson** [usefulness/easylauncher-gradle-plugin#476]
I have noticed recently that my builds on Mac OS don't have the appropriate launcher icon, and instead, a placeholder icon is used. Windows builds of mine don't have this issue. I am unsure how to arrange logs for the plugin, so I am just reporting the issue here.

- App: https://gitlab.com/AuroraOSS/AuroraStore

**Comment by mateuszkwiecinski** [comment]
Please do provide any information that would help to reproduce the issue, ideally a sample project reproducing the issue would be the best. With current information, I can only double-check the CI [runs on Mac OS](https://github.com/usefulness/easylauncher-gradle-plugin/blob/87ede64eca4762508dba39d2becc8a4fa6088701/.github/workflows/default.yml#L168C10-L168C12), so the plugins _works_ 🤷 

Hint for debugging: the only native part the plugin does is WebP decoding/enconding, and it is done via https://github.com/gotson/webp-imageio + recent [6.3.0-SNAPSHOT](https://github.com/usefulness/easylauncher-gradle-plugin/packages/338787) uses newer https://github.com/usefulness/webp-imageio
Output from `uname -mnoprs` command should help you find which architecture specifically your build [tries to load](https://github.com/usefulness/webp-imageio/blob/477311e3e930e55ec9b81cc5a2e9d3b4f4c061c0/webp-imageio/src/main/kotlin/com/luciad/imageio/webp/internal/OsInfo.kt#L37-L72)

**Comment by theimpulson** [comment]
nvm, seems the issue is related to my machine in general
