### ISSUE TITLE
Is `Release` build type supported?

### ISSUE THREAD

**Issue by SamC-Apadmi** [usefulness/easylauncher-gradle-plugin#499]
Hi All

I'm attempting to add banners to the **release** variant of my app. 
Everything works perfectly on debug builds but on release builds the banners are not added.

Simplified version of my config which reproduces the issue:
 
```
easylauncher {
    buildTypes.register("release") {
        enable(true)
        setFilters(grayRibbonFilter("Test"))
    }
}
```

Swapping out `release` for `debug` and running the debug build works perfectly. Not sure if I'm doing something wrong?

**Comment by mateuszkwiecinski** [comment]
Hmm, it should be support, sounds like a bug 👀 As a workaround, you can try to use buildvariant-specific config, so something similar to:
```kotlin
easylauncher {
    variants {
        register("fooRelease") { ...  }
        register("barRelease") { ...  }
        register("bazRelease") { ...  }
    }
```
which I recall was covered with a test and I hope it will work 🤞

**Comment by SamC-Apadmi** [comment]
I think I may have raised this a tad prematurely apologies. 

Your suggestion didn't work, however I tracked down the problem. My `ic_launcher_foreground.xml` file was defined outside of my main app module, in one of my other modules. 

Interestingly on debug builds this wasn't an issue but on release builds it is 🤷 .

Not sure it's worth doing anything about it, but it's good to know!

**Comment by mateuszkwiecinski** [comment]
>My ic_launcher_foreground.xml file was defined outside of my main app module, in one of my other modules.

Yeah, unfortunately that's not supported. You can't access files from outside of your Gradle module. 
To make it work the plugin would have to modify files **after** the resources are merged, but I'm not aware of any Android Gradle Plugin APIs allowing to do so, and the current setup kinda relies on the resource merging process, so it has to hook in _before_ AGP does the resource merging.
