### ISSUE TITLE
Suggestion: Allow defining a custom font

### ISSUE THREAD

**Issue by KieronQuinn** [usefulness/easylauncher-gradle-plugin#56]
This doesn't appear to be possible currently as it's hard coded to "DEFAULT" in the code, but it would be nice to be able to point the plugin to a TTF or OTF file which would allow the usage of, for example, icons from a font icon pack like a dog paw (dogfood) or a bug (debug release). 

The material icon font can be found here if one is required for testing: https://github.com/google/material-design-icons/tree/master/font

**Comment by mateuszkwiecinski** [comment]
Hey @KieronQuinn, thanks for reporting the suggestion! 
I added ability to provide custom font in #59, but that relies on providing a locally installed font name, not on external file, I hope that would work in your case.
I'm not sure I understood what a font icon pack is 🤔 Could you link one?

**Comment by KieronQuinn** [comment]
@mateuszkwiecinski Thanks for implementing it, all looks good. The local font requirement might cause problems for remote continuous integration platforms like Bitrise (but you should be able to install a font as a step during the build so I _think_ the change would be acceptable

An icon font is exactly what it says on the tin - a font containing just icon glyphs. Mostly they're used for web, you include them as a stylesheet and then refer to them with a class that places the icon in using a unicode code point. Material Icons is Google's one, font binaries and code points can be found here: https://github.com/google/material-design-icons/tree/master/font
For example, if you used that font and put the unicode character \ue868 in the gradle file as the text, it should show as a little bug icon in the banner.

**Comment by mateuszkwiecinski** [comment]
Ah right, makes sense! Thanks for explanation. I'll see what can be done there

**Comment by mateuszkwiecinski** [comment]
FYI: I released version 3.3.0 which introduces `ttf` file support. I'll try to add `otf` file once I find some free time. 
I would expect it to work out of the box, given the support has been [introduced in Java7](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6992611), but for some reason it is not recognized properly 🤷

**Comment by KieronQuinn** [comment]
If it's awkward, don't worry about it! I think most icon fonts are provided in TTF as well as OTF anyway and normal fonts are easy to convert for personal use

**Comment by mateuszkwiecinski** [comment]
FYI: It turned out the `otf` file support has been already implemented, but I just was referencing wrong file when testing 🤦 
The plugin supports providing custom font by an otf file. 

Thank you for sharing the idea, that's a really nice improvement 👍
