### ISSUE TITLE
Kotlin DSL friendly

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [usefulness/easylauncher-gradle-plugin#57]
Currently, this plugin is unusable with Kotlin DSL as you can see in the next image, the accessors generated for the lambda is the type `any`:

![image](https://user-images.githubusercontent.com/7463564/92100938-b4cad080-eddc-11ea-9d27-3de8b0d421ff.png)

**Comment by mateuszkwiecinski** [comment]
Thanks for reporting the issue! 
Indeed I set wrong visibility to one of the clases making it unavailable to Kotlin DSL scripts. This should be fixed by #60
Would you be able to confirm if it works for you in version `3.2.0` I'll release in few minutes?

**Comment by JavierMeep** [comment]
Sorry for my late response, I am trying to add again the plugin but I am unable to use `iconNames`. It takes a ListProperty, should be great it uses a list of strings for example

**Comment by JavierSegoviaCordoba** [comment]
Sorry for my late response, I am trying to add again the plugin but I am unable to use iconNames. It takes a ListProperty, should be great it uses a list of strings for example

**Comment by mateuszkwiecinski** [comment]
Hello again @JavierSegoviaCordoba 👋 
so, considering code similar to sample from readme written in Groovy:
```groovy
// `build.gradle`
easylauncher {
    iconNames = ["@mipmap/custom_launcher_icon"]

    buildTypes {
        beta {
            iconNames = ["@mipmap/beta_launcher_1"]  // this overwrites the value
            iconNames += "@mipmap/beta_launcher_2"  // this appends the value
        }
    }
}
```

Here's the same code translated to Kotlin DSL
``` kotlin
// `build.gradle.kts`
easylauncher {
    iconNames.value("@mipmap/custom_launcher_icon") 

    buildTypes {
        register("beta") {
            iconNames.value(listOf("@mipmap/beta_launcher_1") // this overwrites the value
            iconNames.add("@mipmap/beta_launcher_2") // this appends the value
        }
    }
}

```

Here's full `ListProperty` api reference:
https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ListProperty.html

Here's working sample:
https://github.com/mateuszkwiecinski/easylauncher_sample/blob/master/app/build.gradle.kts#L25

Please note I don't have any experience witih Kotlin DSL so there might be more fluent API than using raw Java interface (e.g. a magic extension or delegate). Anyway, hope this helps and will let you move forward 😃

**Comment by JavierSegoviaCordoba** [comment]
The first sample should use `listOf` too. If you fix it I delete this comment 👍🏼 

```
easylauncher {
    iconNames.value(listOf("@mipmap/custom_launcher_icon"))
}
```

**Comment by mateuszkwiecinski** [comment]
Ah sorry 😞 Indeed, there should be `iconNames.value(listOf(..))` as `iconNames` is a `ListProperty`. Thanks for catching that 👍
