### ISSUE TITLE
How to use icon that are part of module resources ?

### ISSUE THREAD

**Issue by afaucogney** [usefulness/easylauncher-gradle-plugin#77]
I have an app where the icon is part of a module ui-kit. If the icon are not available in the main app module, easylauncher doesn't work.
This was the same for the version from Akaita : https://github.com/akaita/easylauncher-gradle-plugin/issues/43

Do you have any way to do that ?

**Comment by mateuszkwiecinski** [comment]
Just to make sure I understand the case correctly:
1. `:app` is main module that contains `AndroidManifest.xml` which has a `android:icon` reference to resource placed in `:ui-kit` module.
2. `ui-kit` is a android library which has only resource, but doesn't reference it in its `AndroidManifest.xml` file. 

Does that describe your case?

**Comment by afaucogney** [comment]
You well understood. I will try to do a example project in the next days.

**Comment by mateuszkwiecinski** [comment]
Ok, so most probably after I #78 is fixed you should be able to apply the plugin to your library module and pass `iconNames` you would like add ribbon to.
I'd appreciate a sample project as that's the most convenient way of making sure it works and will work in the future plugin version, thanks!

by the way, which `AndroidManifest` references your icon resource? Does that take place in your `:app` AndroidManifest or in the `ui-kit`'s which gets merged later? I started wondering if I could detect such case and add out-of-the box support 🤔

**Comment by mateuszkwiecinski** [comment]
FYI: I just released version `3.5.0` which can be applied to your `ui-kit` library (instead of the `app` one) and it should either automatically dicover the icon (if referenced in library `AndroidManifest` file) or you can reference your launcher icons using the new `iconNames` property.

If there are still any problems I'd appreciate sample project that reproduces the issue
