### ISSUE TITLE
Issue: EasyLauncherConfig with name not found

### ISSUE THREAD

**Issue by mikef-dk** [usefulness/easylauncher-gradle-plugin#91]
I'm facing following issue when trying to setup the plugin for any buildType:

> EasyLauncherConfig with name 'debug' not found.

My configuration in `app/build.grade`

```
android {
    // ...

    buildTypes {
        getByName("debug") {
            // ...
        }
    }

    // ...

}

easylauncher {
    buildTypes {
        getByName("debug") {
            chromeLike()
        }
    }
}
```

Why is this not working? I'm not 100% familiar with kts so there is a good chance that I'm missing something.

**Comment by mateuszkwiecinski** [comment]
Hey @mikef-dk 👋 
Use `register("debug")` instead of `getByName("debug")`. The plugin doesn't register any configs by default. 
Normally you'd have to do the same for `android.buildTypes` but Android Gradle Plugin registers both `debug` and `release` automatically and that's why you can _get_ them.

**Comment by mikef-dk** [comment]
Hi @mateuszkwiecinski,

wow, thanks for the amazingly fast reply. `register("debug")` totally solves the problem however the "chromeLike" badge still is not applied to the icon. I tried also other options and apparently none of them work. Is there anything else I have to do. Currently my block looks like this:

```
easylauncher {
    buildTypes {
        register("debug") {
            chromeLike()
        }
    }
}
```

**Comment by mateuszkwiecinski** [comment]
Unfortunately I can't verify that right now, but one of:
```
        register("debug") {
            filters(chromeLike())
         }
```
or `filters = chromeLike()`,  or `setFilters(chromeLike()`, or `setFilters(listOf(chromeLike())`
should work 🤞 

If you're using Android Studio you should have an autocomplete suggestion on how to set the filters (it worked for me when fixing kts support https://github.com/usefulness/easylauncher-gradle-plugin/pull/60)

**Comment by mikef-dk** [comment]
I was about to post that as well but once again you were faster than me. ;)

You're right: `filters(chromeLike())` is the correct call.

```
easylauncher {
    buildTypes {
        register("debug") {
            filters(chromeLike())
        }
    }
}
```

Everything works perfectly now. Thanks again for your help. Maybe I'll add a *.kts sample to the project. ;)

**Comment by mateuszkwiecinski** [comment]
You're welcome 👍 I'll try improve the decumentation to somehow mention kotlin scripts and, as you pointed out, I should also update [kts sample](https://github.com/usefulness/easylauncher-gradle-plugin/blob/master/sample/example-scripted/build.gradle.kts) which clearly doesn't showcase custom filters 😞
