### ISSUE TITLE
Round Icons are not generated

### ISSUE THREAD

**Issue by matecode** [usefulness/easylauncher-gradle-plugin#95]
Short error description:
Beside `android:icon="@mipmap/ic_launcher"` I defined `android:roundIcon="@mipmap/ic_launcher_round"` in the manifest, but easylauncher does not generate the icons in `build/generated/res/.../mipmap-.../`

**Comment by mateuszkwiecinski** [comment]
Hey @matecode 👋 
Thanks for reporting the issue 👍  Indeed, the plugin skips adding ribbon to resources provided as `android:roundIcon`.
This should be fixed in #96. If it passes the build I'll release new version and hopefully the your issue will be resolved.

**Comment by mateuszkwiecinski** [comment]
Fixed in [3.7.0](https://github.com/usefulness/easylauncher-gradle-plugin/releases/tag/release-3.7.0)
